### ISSUE TITLE
Way to get a representative transcript for each cluster.

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Oshlack/Corset#10]
```
As the title says. 

Would need to be an independent tool.
```

Original issue reported on code.google.com by `nadiamda...@gmail.com` on 19 Dec 2014 at 6:09

**Comment by CJ-Chen** [comment]
Most people might use the 'longest seq' in one cluser as its representative transcripts
If u thinks so, just TWO command will finished the task.

# check how many transcripts were input into corset (optional)
# cut -f1 clusters-0.3.txt|sort|uniq|wc -l
# 80829
# check how many clusters were output by corset (optional)
# cut -f2 clusters-0.3.txt|sort|uniq|wc -l
# 49581
# 
# Add cluster in fasta file use the tool in corset package
**corset_fasta_ID_changer clusters-0.3.txt Trinity.fasta > Trinity.idmod.fasta**
# Get the Longest transcript
**perl -e 'my $file=shift;my $sigPattern=shift;my $label_pattern=q{^>};my $ref=&Single_Label_Reader($file,$label_pattern);my $content;while($content=&$ref){my ($label,@content)=@$content;$seq=join q{},@content;$seq=~s/[\r\n]//g;($sig=$label)=~s/$sigPattern/$1/;$seenLen{$sig}=length($seq) if $seenLen{$sig}<length($seq);}my $ref=&Single_Label_Reader($file,$label_pattern);my $content;while($content=&$ref){my ($label,@content)=@$content;$seq=join q{},@content;$seq=~s/[\r\n]//g;($sig=$label)=~s/$sigPattern/$1/;if ($seenLen{$sig}<=length($seq)){print $label,@content unless $out{$sig}++ || $label=~/UnknownCluster--/;};}sub Single_Label_Reader {my $file=shift;my $label_pattern=shift;die "Error:$file unreachable.\n" unless (-s $file);open IN,q{<},$file or die "Error:$file unreadable.\n";my $temp1=<IN>;my $temp2=$temp1;my @temp;return sub {return q{} if (eof(IN));while(!eof(IN)){$temp1=$temp2;@temp=();while(<IN>){if (/$label_pattern/){$temp2=$_;last;}push @temp,$_;}return [$temp1,@temp];}}}' Trinity.idmod.fasta '(>Cluster-\d+\.\d+)--.*$' > Trinity.longestInCluster.fasta**
# check the result (optional)
# grep -c '^>' Trinity.longestInCluster.fasta 
# 49581

**Comment by nadiadavidson** [comment]
We have also now developed Lace for this, https://github.com/Oshlack/Lace.
