### ISSUE TITLE
stuck after reading bam file?

### ISSUE THREAD

**Issue by JPascualAnaya** [Oshlack/Corset#15]
Hi there, 

I am running Corset over a large set of mapped reads, and actually was wondering whether it is normal to see no advance for 3 days, while the program seems to be running...

This is the beginning and end of the stdout, which I am redirecting to a log file:

```
$ head corset_default.log 

Running Corset Version 1.07
Reading bam file : bowtie2.for.corset.bam
0 million alignments read
0.2 million alignments read
0.4 million alignments read
0.6 million alignments read
0.8 million alignments read
1 million alignments read
1.2 million alignments read

```
```
$ tail corset_default.log 
-862.6 million alignments read
-862.4 million alignments read
-862.2 million alignments read
-862 million alignments read
-861.8 million alignments read
-861.6 million alignments read
-861.4 million alignments read
-861.2 million alignments read
-861 million alignments read
Done reading bowtie2.for.corset.bam

```
It's been like that for 3 days now, so is it just stuck, or is it normal that there's no more messages after finishing reading the bam file but still working?

Thanks in advance!
Cheers,
Juan

**Comment by nadiadavidson** [comment]
Sorry I didn't see this issue earlier. In case you haven't already moved on, I'm happy to investigate. The tail of the output look very strange as it counting backwards and reporting negative numbers! Do you have a reproducible example you could share with me?

**Comment by JPascualAnaya** [comment]
Hi Nadia, thank you for your reply.
Unfortunately, I ended up giving up on it and don't have the files anymore. 
When I use corset again, if I run into the same issue I'll let you know.
