### ISSUE TITLE
How does Corset deal with chimeric mis-assemblies?

### ISSUE THREAD

**Issue by chocotwig** [Oshlack/Corset#19]
Hi, 
Say I have a transcript assembled as two different isoforms of the same trinity gene (eg. DN1234_c0_g1_i1 and i2). They are almost identical to each other for 1500 bp, but i2 has an extra 1000 bp that corresponds to another gene missasembled with that contig. Would Corset count these two in the same cluster?

Thanks!

**Comment by nadiadavidson** [comment]
Sorry, only just saw this message. This is actually a fairly common scenario. There are two things that would happen in this case. 1) If the two genes have very different fold changes between conditions, e.g. one gene is strongly differentially expressed and the other is not, then corset will split DN1234_c0_g1_i1 and DN1234_c0_g1_i2 into different clusters. Shared reads will be randomly assigned to a cluster so DN1234_c0_g1_i1 will have roughly half the counts for your gene. DN1234_c0_g1_i2 would have a mixture of counts from both genes. 2) If DN1234_c0_g1_i1 and i2 have similar fold changes between conditions, they will not be split into different cluster. Then the cluster and counts will be a mixture of the two genes.
